import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import Button from "../public/UI/Button";
import Nav from "../public/UI/Nav";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <div className={styles.home}>
        <div>
          <h1>Cornell Photography</h1>        
          <Button name="Sign In"/>
        </div>
      </div>
    </div>
  );
}
