import Head from "next/head";
import React, { useEffect, useState, useContext } from "react";
import styles from "../styles/Home.module.css";
import Button from "../public/UI/Button";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {props.isSignedIn ? (
        <p className={styles.homeUser}>Hello {props.user.username}</p>
      ) : (
        <div className={styles.home}>
          (
          <div>
            <h1>Cornell Photography</h1>
            <Button name="Sign In With Google" onClick={props.signIn} />
          </div>
          )
        </div>
      )}
    </div>
  );
}
